update

diff --git a/git-secrets b/git-secrets
--- a/git-secrets
+++ b/git-secrets
@@ -137,20 +137,20 @@ process_output() {
 }
 
 # Calls the given scanning function at $1, shifts, and passes to it $@.
-# Exit 0 if success, otherwise exit 1 with error message.
+# Return 0 if success, otherwise exit 1 with error message.
 scan_with_fn_or_die() {
   local fn="$1"; shift
   $fn "$@" && return 0
   echo >&2
-  echo "[ERROR] Matched one or more prohibited patterns" >&2
+  echo "[ERROR] 发现包含敏感信息 -- " >&2
   echo >&2
-  echo "Possible mitigations:" >&2
-  echo "- Mark false positives as allowed using: git config --add secrets.allowed ..." >&2
-  echo "- Mark false positives as allowed by adding regular expressions to .gitallowed at repository's root directory" >&2
-  echo "- List your configured patterns: git config --get-all secrets.patterns" >&2
-  echo "- List your configured allowed patterns: git config --get-all secrets.allowed" >&2
-  echo "- List your configured allowed patterns in .gitallowed at repository's root directory" >&2
-  echo "- Use --no-verify if this is a one-time false positive" >&2
+  echo "解决办法:" >&2
+  echo "- 移除敏感信息并重新扫描： git secrets --scan" >&2
+  echo "- 执行命令来设置额外允许: git config --add secrets.allowed ..." >&2
+  echo >&2
+  echo "其他帮助:" >&2
+  echo "- 列出所有的检查规则: git config --get-all secrets.patterns" >&2
+  echo "- 列出所有的额外允许: git config --get-all secrets.allowed" >&2
   exit 1
 }
 
@@ -313,6 +313,8 @@ if [ ${RECURSIVE} -eq 1 ]; then
   # SCAN_UNTRACKED=1
 fi
 
+# git secrets --install -g
+# git secrets --scan
 case "${COMMAND}" in
   -h|--help|--) "$0" -h; exit 0 ;;
   --commit_msg_hook|--pre_commit_hook|--prepare_commit_msg_hook)
