release 1.0

diff --git a/git-secrets b/git-secrets
--- a/git-secrets
+++ b/git-secrets
@@ -25,6 +25,7 @@ add Adds a prohibited or allowed pattern, ensuring to de-dupe with existing patt
 r,recursive --scan scans directories recursively
 cached --scan scans searches blobs registered in the index file
 no-index --scan searches files in the current directory that is not managed by Git
+no-history --scan only scan current latest files
 untracked In addition to searching in the tracked files in the working tree, --scan also in untracked files
 f,force --install overwrites hooks if the hook already exists
 l,literal --add and --add-allowed patterns are escaped so that they are literal
@@ -142,10 +143,10 @@ scan_with_fn_or_die() {
   local fn="$1"; shift
   $fn "$@" && return 0
   echo >&2
-  echo "[ERROR] 发现包含敏感信息 -- " >&2
+  echo "[ERROR] 发现敏感信息 " >&2
   echo >&2
   echo "解决办法:" >&2
-  echo "- 移除敏感信息并重新扫描： git secrets --scan" >&2
+  echo "- 移除敏感信息并重新扫描: git secrets --scan" >&2
   echo "- 执行命令来设置额外允许: git config --add secrets.allowed ..." >&2
   echo >&2
   echo "其他帮助:" >&2
@@ -260,7 +261,7 @@ assert_option_for_command() {
 }
 
 declare COMMAND="$1" FORCE=0 RECURSIVE=0 LITERAL=0 GLOBAL=0 ALLOWED=0
-declare SCAN_CACHED=0 SCAN_NO_INDEX=0 SCAN_UNTRACKED=0
+declare SCAN_CACHED=0 SCAN_NO_INDEX=0 SCAN_UNTRACKED=0 SCAN_NO_HISTORY=0
 
 # Shift off the command name
 shift 1
@@ -293,6 +294,10 @@ while [ "$#" -ne 0 ]; do
     --untracked)
       assert_option_for_command "--scan" "--untracked"
       SCAN_UNTRACKED=1
+      ;;
+    --no-history)
+      assert_option_for_command "--scan" "--no-history"
+      SCAN_NO_HISTORY=1
       ;;
     -g) GLOBAL=1 ;;
     --) shift; break ;;
@@ -329,7 +334,10 @@ case "${COMMAND}" in
     ;;
   --scan) 
     scan_with_fn_or_die "scan" "$@" 
-    scan_with_fn_or_die "scan_history" "$@"
+    if [ ${SCAN_NO_HISTORY} -eq 0 ]; then
+      scan_with_fn_or_die "scan_history" "$@"
+    fi
+    echo "You Are Safe !!"
     ;;
   --list)
     if [ ${GLOBAL} -eq 1 ]; then
